# Generated by Django 4.2.4 on 2023-08-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecollection',
            options={'ordering': ['id']},
        ),
    ]
