# Generated by Django 4.2.4 on 2023-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_user_alter_studio_games_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
