# Generated by Django 4.2.4 on 2023-08-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_genre_game_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newgame',
        ),
    ]
