# Generated by Django 4.2.4 on 2023-08-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_newgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.studio'),
        ),
    ]
